config/routes.rb
Rails.application.routes.draw do
  concern :oai_provider, BlacklightOaiProvider::Routes.new

  mount Riiif::Engine => 'images', as: :riiif if Hyrax.config.iiif_image_server?

  if Settings.multitenancy.enabled
    constraints host: Account.admin_host do
      get '/account/sign_up' => 'account_sign_up#new', as: 'new_sign_up'
      post '/account/sign_up' => 'account_sign_up#create'
      get '/', to: 'splash#index'

      # pending https://github.com/projecthydra-labs/hyrax/issues/376
      get '/dashboard', to: redirect('/')

      namespace :proprietor do
        resources :accounts
        resources :users
      end
    end
  end

  get 'status', to: 'status#index'

  mount BrowseEverything::Engine => '/browse'
  resource :site, only: [:update] do
    resources :roles, only: [:index, :update]
    resource :labels, only: [:edit, :update]
    resource :contact, only: [:edit, :update]
  end

  root 'hyrax/homepage#index'

  devise_for :users, controllers: { invitations: 'hyku/invitations', registrations: 'hyku/registrations' }
  mount Qa::Engine => '/authorities'

  mount Blacklight::Engine => '/'
  mount Hyrax::Engine, at: '/'
  if Settings.bulkrax.enabled
    mount Bulkrax::Engine, at: '/'
  end

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  curation_concerns_basic_routes

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :oai_provider

    concerns :searchable
  end

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  namespace :admin do
    resource :account, only: [:edit, :update]
    resource :work_types, only: [:edit, :update]
    resources :users, only: [:destroy]
    resources :groups do
      member do
        get :remove
      end

      resources :users, only: [:index], controller: 'group_users' do
        collection do
          post :add
          delete :remove
        end
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Includes lib/rolify from the rolify gem
  rolify
  # Connects this user object to Hydra behaviors.
  include Hydra::User
  # Connects this user object to Hyrax behaviors.
  include Hyrax::User
  include Hyrax::UserUsageStats

  attr_accessible :email, :password, :password_confirmation if Blacklight::Utils.needs_attr_accessible?
  # Connects this user object to Blacklights Bookmarks.
  include Blacklight::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :invitable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :add_default_roles

  scope :for_repository, -> {
    joins(:roles)
  }

  # Method added by Blacklight; Blacklight uses #to_s on your
  # user class to get a user-displayable login/identifier.
  def to_s
    email
  end

  def is_superadmin
    has_role? :superadmin
  end

  # This comes from a checkbox in the proprietor interface
  # Rails checkboxes are often nil or "0" so we handle that
  # case directly
  def is_superadmin=(value)
    value = ActiveModel::Type::Boolean.new.cast(value)
    if value
      add_role :superadmin
    else
      remove_role :superadmin
    end
  end

  def site_roles
    roles.site
  end

  def site_roles=(roles)
    roles.reject!(&:blank?)

    existing_roles = site_roles.pluck(:name)
    new_roles = roles - existing_roles
    removed_roles = existing_roles - roles

    new_roles.each do |r|
      add_role r, Site.instance
    end

    removed_roles.each do |r|
      remove_role r, Site.instance
    end
  end

  def groups
    return ['admin'] if has_role?(:admin, Site.instance)
    []
  end

  # If this user is the first user on the tenant, they become its admin
  # unless we are in the global tenant
  def add_default_roles
    add_role :admin, Site.instance unless
      self.class.joins(:roles).where("roles.name = ?", "admin").any? || Account.global_tenant?
    # Role for any given site
    add_role :registered, Site.instance
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < AdminController
    before_action :load_user, only: [:destroy]

    # NOTE: User creation/invitations handled by devise_invitable

    # Delete a user from the site
    def destroy
      if @user.present? && @user.roles.destroy_all
        redirect_to hyrax.admin_users_path, notice: t('hyrax.admin.users.destroy.success', user: @user)
      else
        redirect_to hyrax.admin_users_path flash: { error: t('hyrax.admin.users.destroy.failure', user: @user) }
      end
    end

    private

      def load_user
        @user = User.from_url_component(params[:id])
      end
  end
end

app/controllers/proprietor/accounts_controller.rb
# frozen_string_literal: true

module Proprietor
  class AccountsController < ProprietorController
    before_action :ensure_admin!

    load_and_authorize_resource

    # GET /accounts
    # GET /accounts.json
    def index
      authorize! :manage, Account
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.admin.sidebar.accounts'), proprietor_accounts_path
    end

    # GET /accounts/1
    # GET /accounts/1.json
    def show
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.admin.sidebar.accounts'), proprietor_accounts_path
      add_breadcrumb @account.tenant, edit_proprietor_account_path(@account)
    end

    # GET /accounts/new
    def new
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.admin.sidebar.accounts'), proprietor_accounts_path
      add_breadcrumb 'New account', new_proprietor_account_path
    end

    # GET /accounts/1/edit
    def edit
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.admin.sidebar.accounts'), proprietor_accounts_path
      add_breadcrumb @account.tenant, edit_proprietor_account_path(@account)
    end

    # POST /accounts
    # POST /accounts.json
    def create
      respond_to do |format|
        create_account = CreateAccount.new(@account, super_and_current_users)
        if create_account.save
          format.html { redirect_to [:proprietor, @account], notice: 'Account was successfully created.' }
          format.json { render :show, status: :created, location: @account.cname }
        else
          format.html { render :new }
          format.json { render json: @account.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /accounts/1
    # PATCH/PUT /accounts/1.json
    def update
      respond_to do |format|
        if @account.update(account_params)
          format.html { redirect_to [:proprietor, @account], notice: 'Account was successfully updated.' }
          format.json { render :show, status: :ok, location: [:proprietor, @account] }
        else
          format.html { render :edit }
          format.json { render json: @account.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /accounts/1
    # DELETE /accounts/1.json
    def destroy
      CleanupAccountJob.perform_now(@account)

      respond_to do |format|
        format.html { redirect_to proprietor_accounts_url, notice: 'Account was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

      def ensure_admin!
        authorize! :read, :admin_dashboard
      end

      # Never trust parameters from the scary internet, only allow the permitted parameters through.
      def account_params
        params.require(:account).permit(:name, :cname, :title,
                                        admin_emails: [],
                                        solr_endpoint_attributes: %i[id url],
                                        fcrepo_endpoint_attributes: %i[id url base_path])
      end
  end
end

app/controllers/proprietor/users_controller.rb
# frozen_string_literal: true

module Proprietor
  class UsersController < ProprietorController
    before_action :ensure_admin!

    before_action :find_user, only: %i[show edit update destroy]
    load_and_authorize_resource

    # GET /users
    # GET /users.json
    def index
      authorize! :manage, User
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.admin.sidebar.users'), proprietor_users_path
    end

    # GET /users/1
    # GET /users/1.json
    def show
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.admin.sidebar.users'), proprietor_users_path
      add_breadcrumb @user.display_name, edit_proprietor_user_path(@user)
    end

    # GET /users/new
    def new
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.admin.sidebar.users'), proprietor_users_path
      add_breadcrumb 'New user', new_proprietor_user_path
    end

    # GET /users/1/edit
    def edit
      add_breadcrumb t(:'hyrax.controls.home'), root_path
      add_breadcrumb t(:'hyrax.admin.sidebar.users'), proprietor_users_path
      add_breadcrumb @user.display_name, edit_proprietor_user_path(@user)
    end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)
      respond_to do |format|
        if @user.valid? && @user.save
          format.html { redirect_to proprietor_users_path, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: [:proprietor, @user] }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to proprietor_users_path, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: [:proprietor, @user] }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      message = if @user.destroy
                  'User was successfully destroyed.'
                else
                  'User could not be destroyed.'
                end

      respond_to do |format|
        format.html { redirect_to proprietor_users_url, notice: message }
        format.json { head :no_content }
      end
    end

    private

      def ensure_admin!
        authorize! :read, :admin_dashboard
      end

      def user_params
        # remove blank passwords
        params[:user].delete(:password) if params[:user] && params[:user][:password].blank?

        params.require(:user).permit(:email,
                                     :password,
                                     :is_superadmin,
                                     :facebook_handle,
                                     :twitter_handle,
                                     :googleplus_handle,
                                     :display_name,
                                     :address,
                                     :department,
                                     :title,
                                     :office,
                                     :chat_id,
                                     :website,
                                     :affiliation,
                                     :telephone,
                                     :avatar,
                                     :group_list,
                                     :linkedin_handle,
                                     :orcid,
                                     :arkivo_token,
                                     :arkivo_subscription,
                                     :zotero_token,
                                     :zotero_userid,
                                     :preferred_locale,
                                     role_ids: [])
      end

      def find_user
        @user ||= ::User.from_url_component(params[:id])
        raise ActiveRecord::RecordNotFound unless @user
      end
  end
end

app/controllers/proprietor_controller.rb
# frozen_string_literal: true

class ProprietorController < ApplicationController
  skip_before_action :require_active_account!
  layout "proprietor"
end

app/views/proprietor/users/_form.html.erb
<div class="form-inputs">
  <%= f.input :display_name, label: 'Display Name' %>
  <%= f.input :email, hint: '' %>
  <%= f.input :is_superadmin, as: :boolean %>
  <%= f.input :password, hint: 'Only if creating or changing' %>
  <%= f.input :facebook_handle %>
  <%= f.input :twitter_handle %>
  <%= f.input :googleplus_handle %>
  <%= f.input :address %>
  <%= f.input :department %>
  <%= f.input :title, hint: '' %>
  <%= f.input :office %>
  <%= f.input :chat_id %>
  <%= f.input :website %>
  <%= f.input :affiliation %>
  <%= f.input :telephone %>
  <%= f.input :avatar %>
  <%= f.input :group_list %>
  <%= f.input :linkedin_handle %>
  <%= f.input :orcid %>
  <%= f.input :arkivo_token %>
  <%= f.input :arkivo_subscription %>
  <%= f.input :preferred_locale %>
</div>

app/views/proprietor/users/edit.html.erb
<% content_for :page_header do %>
  <h1><span class="fa fa-gears"></span> <%= t(".header") %></h1>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default user-form">
      <%= simple_form_for @user, url: [:proprietor, @user], html: { class: 'form' } do |f| %>
        <div class="panel-body">
          <% if @user.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
              <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
              <ul>
                <% @user.errors.messages.each do |key, messages| %>
                  <li><%= key %> &quot;<%= @user.errors&.details[key]&.first&.[](:value) %>&quot; <%= messages.join(' and ') %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <%= render 'form', user: @user, f: f %>

          <%= f.submit class: 'btn btn-primary' %>
          <%= link_to t('simple_form.cancel'), proprietor_users_path, class: 'btn btn-link action-cancel' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/proprietor/users/index.html.erb
<% content_for :page_header do %>
  <h1><span class="fa fa-gears"></span> <%= t('.header') %></h1>
  <div class="pull-right">
    <%= link_to new_proprietor_user_path, class: 'btn btn-primary' do %>
      <span class="fa fa-edit"></span> <%= t('.create_new') %>
    <% end %>
  </div>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table table-striped datatable">
          <thead>
            <tr>
              <th><%= t('.email') %></th>
              <th><%= t('.display_name') %></th>
              <th><%= t('.department') %></th>
              <th><%= t('.title') %></th>
              <th><%= t('.affiliation') %></th>
              <th><%= t('.superadmin') %></th>
              <th><%= t('.actions') %></th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.email %></td>
                <td><%= user.display_name %></td>
                <td><%= user.department %></td>
                <td><%= user.title %></td>
                <td><%= user.affiliation %></td>
                <td><%= user.is_superadmin %></td>
                <td class="col-md-2"><%= link_to t('.manage'), proprietor_user_path(user) %>&nbsp;|&nbsp;<%= link_to t('helpers.action.edit'), edit_proprietor_user_path(user) %>&nbsp;|&nbsp;<%= link_to t('helpers.action.delete'), proprietor_user_path(user), method: :delete, data: { confirm: t('.confirm_delete') } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/proprietor/users/new.html.erb
<% content_for :page_header do %>
  <h1><span class="fa fa-gears"></span> <%= t('.header') %></h1>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default user-form">
      <%= simple_form_for @user, url: [:proprietor, @user], html: { class: 'form' } do |f| %>
        <div class="panel-body">
            <% if @user.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
                <%= pluralize(@user.errors.count, "error") %> prohibited this repository from being saved:
                <ul>
                  <% @user.errors.messages.each do |key, messages| %>
                    <li><%= key %> &quot;<%= @user.errors.details[key].first[:value] %>&quot; <%= messages.join(' and ') %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <%= render 'form', user: @user, f: f %>

            <%= f.submit class: 'btn btn-primary' %>
            <%= link_to t('simple_form.cancel'), proprietor_users_path, class: 'btn btn-link action-cancel' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/proprietor/users/show.html.erb
<% content_for :page_header do %>
  <h1><span class="fa fa-gears"></span> <%= t('.header') %></h1>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-sm-10">
            <h2><%= @user.display_name %> (<%= @user.email %>)</h2>
          </div>
          <div class="col-sm-2">
            <div class="pull-right">
              <%= link_to edit_proprietor_user_path(@user), class: 'btn btn-primary' do %>
                <span class="fa fa-edit"></span> <%= t('.edit') %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <%= simple_form_for @user, url: [:proprietor, @user], html: { class: 'form' } do |f| %>
          <div class="form-group">
            <%= f.association :roles, as: :check_boxes %>
          </div>
          <%= f.submit t('.update'), class: 'btn btn-primary' %>
          <%= link_to t('simple_form.cancel'), proprietor_users_path, class: 'btn btn-link action-cancel' %>
        <% end %>
      </div>
    </div>
  </div>
</div>